name: Test

on:
  - pull_request
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node Version
        run: node --version
      - name: npm Version
        run: npm --version
      - name: 'Install dependencies'
        run: npm ci
      - name: Run linting and Tests
        run: npm run test:prod
      - name: Upload dist bundle
        uses: actions/upload-artifact@v2
        with:
          name: test-build
          path: distribution
      - name: Run web-ext lint
        run: npm run lint:web-ext
      - name: Codecov Upload
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
